services:
  vehicle-manager-service:
    build:
      context: ../vehicle-manager-service
      dockerfile: Dockerfile
    ports:
      - '3002:3002'
    environment:
      DYNAMODB_ENDPOINT: http://localstack:4566
      AWS_REGION: us-east-1
      DYNAMODB_TABLE: Vehicles
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
    depends_on:
      - localstack
    networks:
      - vehicle-network

  vehicle-sales-service:
    build:
      context: ../vehicle-sales-service
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    environment:
      DYNAMODB_ENDPOINT: http://localstack:4566
      VEHICLE_MANAGER_SERVICE_API: http://vehicle-manager-service:3002
      AWS_REGION: us-east-1
      DYNAMODB_TABLE: Sales
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
    depends_on:
      - localstack
    networks:
      - vehicle-network

  localstack:
    image: localstack/localstack:latest
    ports:
      - '4566:4566'
    environment:
      - SERVICES=dynamodb
    volumes:
      - localstack_data:/var/lib/localstack
    networks:
      - vehicle-network

networks:
  vehicle-network:

volumes:
  localstack_data: